### ISSUE TITLE
Add mbgrd2gltf standalone program

### ISSUE THREAD

**Issue by MBARIMike** [dwcaress/MB-System#1257]
I think it would be very useful to have a program that would convert bathymetry .grd files to glTF format.

The glTF file format optimizes 3D geometric mesh data for efficient rendering via webgl in web browsers.

A C++ program written by CSUMB Computer Science students has been contributed to the STOQS project: https://github.com/stoqs/stoqs/pull/1175

It relies on C++11, CMake, and the [TinyGLTF library](https://github.com/syoyo/tinygltf).

@dwcaress do you see any issues with this addition to MB-System?

If it's okay then I can take a stab at writing a grd2gltf module as I think MB-System is a better home for it than STOQS.

**Comment by dwcaress** [comment]
Mike,

This would be great, please go ahead.

There are some potentially complicated consequences we'll have to deal with.

This will make the tinygltf library a dependency for MB-System. How widespread is it? There is not an existing Homebrew formula. Is it included in the packages commonly available for Ubuntu, etc? The tinygltf code seems unremarkable and dependent only on JSON, so we could probably embed it into the MB-System distribution so that building can still be accomplished with all dependencies installed by package managers. Otherwise, it would need to be an optional target that is not built by default.

Why do you want to write this as a GMT module as opposed to a standalone program? Unless there is something driving you to embed it in GMT, please write it as a standalone.

**Comment by MBARIMike** [comment]
I don't know how widespread tinygltf is. It seems that it is simply the tiny_gltf .h file and a LICENSE file (MIT) file that needs to be with it. I will attempt to add these files and test the builds.

I was thinking that a mbgrd2gltf module would mimic `src/gmt/mbgrd2obj.c` with the difference being gltf (or .glb) output vice obj output. I think the path is clearer for me to write a standalone program as that is closer to what @ikehirzel has contributed to the STOQS project.

Should the new code go into a new `src/mbgrd2gltf` directory?

**Comment by dwcaress** [comment]
Yes, do a standalone program in which you include the tiny_gltf.h file and the license file that goes with it in a directory src/mbgrd2gltf along with the code for the program mbgrd2gltf.

**Comment by MBARIMike** [comment]
I'm doing my work using the Docker container build. After things are working there I plan to see that it will build using the package managers. One other dependency is a C++ api to the netCDF4 library. I've added https://github.com/Unidata/netcdf-cxx4 to the Docker build, which also required a 'build from source' the underlying netCDF4 C library. I'm a little concerned how this will impact fulfilling MB-Systems dependencies with package manager installations.

**Comment by MBARIMike** [comment]
CSUMB Computer Science capstone project team members @NAPF1, @kdowling99, @julesfortin, and @jesseb92 completed  https://github.com/dwcaress/MB-System/pull/1357 during the Spring 2023 semester, which is why the PR referenced above was closed without merging. 

Nice work! 👏
