### ISSUE TITLE
GSF 3.09

### ISSUE THREAD

**Issue by schwehr** [dwcaress/MB-System#281]
Leidos has GSF 3.09 available on their site.  

We could really use something in the makefile to force Unix formatted files (dos2unix) with the correct bits set and a few patches be applied on updating.  The 3.08 update looks to have stepped on a few of those things.

Also, still no sign of tests, test files, or real revision history in upstream.  We should be extra wary of regressions with this style of code.

Zip is here: 
https://www.leidos.com/products/ocean-marine

I have not checked to see if any of the issues in my fork if GSF were addressed in upstream.  Many of the issues are related to extra testing of GSF that could be move to MB-System.  That testing could/should be copied to MB-System.

https://github.com/schwehr/generic-sensor-format/issues

**Comment by dwcaress** [comment]
Kurt,

Thanks for the heads up. It looks like I did get the release notice back in May, but didn’t handle it right away and then forgot about it.

I always have to make a few changes to the preprocessor calls in the GSF source in order to make it work with MB-System.

Cheers,
Dave


> On Jul 30, 2019, at 8:51 PM, Kurt Schwehr <notifications@github.com> wrote:
> 
> Leidos has GSF 3.09 available on their site.
> 
> We could really use something in the makefile to force Unix formatted files (dos2unix) with the correct bits set and a few patches be applied on updating. The 3.08 update looks to have stepped on a few of those things.
> 
> Also, still no sign of tests, test files, or real revision history in upstream. We should be extra wary of regressions with this style of code.
> 
> Zip is here:
> https://www.leidos.com/products/ocean-marine
> 
> I have not checked to see if any of the issues in my fork if GSF were addressed in upstream. Many of the issues are related to extra testing of GSF that could be move to MB-System. That testing could/should be copied to MB-System.
> 
> https://github.com/schwehr/generic-sensor-format/issues
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

----------------------------------------------------
David W. Caress
Principal Engineer
Seafloor Mapping Lab

Monterey Bay Aquarium Research Institute
7700 Sandholdt Road
Moss Landing, CA 95039

caress@mbari.org
http://www.mbari.org/~caress/

Phone: 831-775-1775

**Comment by schwehr** [comment]
Update done by @dwcaress in https://github.com/dwcaress/MB-System/commit/35e48cf0c1248da29629f09ecd97bf39e804143c
